---
title: "Racial Demographics of Pima County, AZ"
author: "Jacob Hansen"
date: "2/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidycensus)
census_api_key("bc6535753047a343a531d92be52cfa8b40d17182", install = TRUE, overwrite = TRUE)
readRenviron("~/.Renviron")
```

```{r, include=FALSE}
racevars <- c(White = "B02001_002", 
              Black = "B02001_003", 
              Asian = "B02001_005",
              Hispanic = "B03003_003")
maricopa <- get_acs(geography = "tract",
                  variables = racevars, 
                  year = 2018,
                  state = "AZ",
                  county = "Maricopa County",
                  geometry = TRUE,
                  summary_var = "B02001_001")
```

```{r, echo=FALSE, message=FALSE}
maricopa %>%
  mutate(Percent = 100 * (estimate / summary_est)) %>%
  ggplot(aes(fill = Percent, color = Percent)) +
  facet_wrap(~ variable) +
  geom_sf() +
  scale_fill_viridis_c(direction = -1) +
  scale_color_viridis_c(direction = -1) +
  labs(title = "Racial geography of Maricopa County, Arizona",
       caption = "Source: American Community Survey 2014-2018") +
  theme_void()
```

